// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxWEyLGzWuct16ct6VBmFERfuXdJ7meI',
    appId: '1:419963569611:web:f164fce13dbd39a769e24e',
    messagingSenderId: '419963569611',
    projectId: 'pharmatrack-190a8',
    authDomain: 'pharmatrack-190a8.firebaseapp.com',
    storageBucket: 'pharmatrack-190a8.firebasestorage.app',
    measurementId: 'G-LQQT4ZXE38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Rww7ZRPnB26z3JxzbGUTYuCKuFh977E',
    appId: '1:419963569611:android:c39ff3a001a36eab69e24e',
    messagingSenderId: '419963569611',
    projectId: 'pharmatrack-190a8',
    storageBucket: 'pharmatrack-190a8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGxWEyLGzWuct16ct6VBmFERfuXdJ7meI',
    appId: '1:419963569611:web:eb7a15aa92615e1b69e24e',
    messagingSenderId: '419963569611',
    projectId: 'pharmatrack-190a8',
    authDomain: 'pharmatrack-190a8.firebaseapp.com',
    storageBucket: 'pharmatrack-190a8.firebasestorage.app',
    measurementId: 'G-S18TL9EWPY',
  );
}
